# Generated by Django 5.2 on 2025-05-07 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentweather',
            name='generationtime',
            field=models.FloatField(default=0.0),
        ),
    ]
