# Generated by Django 5.2 on 2025-05-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0002_currentweather_generationtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentweather',
            old_name='current',
            new_name='currentValues',
        ),
    ]
