# Generated by Django 5.2 on 2025-05-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0003_rename_current_currentweather_currentvalues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentweather',
            name='generationtime',
        ),
        migrations.AddField(
            model_name='currentweather',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
