# Generated by Django 5.2 on 2025-05-21 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0004_remove_currentweather_generationtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentweather',
            old_name='currentValues',
            new_name='current',
        ),
    ]
