# Generated by Django 5.2 on 2025-05-21 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0005_rename_currentvalues_currentweather_current'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currentweather',
            old_name='currentUnits',
            new_name='current_units',
        ),
    ]
