# Generated by Django 5.2 on 2025-05-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_api', '0006_rename_currentunits_currentweather_current_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord', models.JSONField()),
                ('weather', models.JSONField()),
                ('base', models.CharField()),
                ('main', models.JSONField()),
                ('visibility', models.CharField()),
                ('wind', models.JSONField()),
                ('clouds', models.JSONField()),
                ('dt', models.IntegerField()),
                ('sys', models.JSONField()),
                ('timezone', models.CharField()),
                ('name', models.CharField()),
                ('cod', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
